module.exports = {
  env: {
    browser: true,
    node: true,
  },
  extends: 'eslint:recommended',
  rules: {
    'guard-for-in': 2,
    'no-caller': 2,
    'no-extend-native': 2,
    'no-extra-bind': 2,
    'no-invalid-this': 2,
    'no-multi-spaces': 2,
    'no-multi-str': 2,
    'no-new-wrappers': 2,
    'no-with': 2,

    'array-bracket-spacing': [2, 'never'],
    'block-spacing': [2, 'never'],
    'brace-style': 2,
    'comma-dangle': [2, 'always-multiline'],
    'comma-spacing': 2,
    'comma-style': 2,
    'computed-property-spacing': 2,
    'eol-last': 2,
    'func-call-spacing': 2,
    'key-spacing': 2,
    'keyword-spacing': 2,
    'linebreak-style': 2,
    'max-len': [
      2,
      {
        code: 80,
        tabWidth: 2,
        ignoreUrls: true,
      },
    ],
    'new-cap': 2,
    'no-array-constructor': 2,
    'no-multiple-empty-lines': [2, {max: 2}],
    'no-new-object': 2,
    'no-tabs': 2,
    'no-trailing-spaces': 2,
    'object-curly-spacing': 2,
    'one-var': [
      2,
      {
        var: 'never',
        let: 'never',
        const: 'never',
      },
    ],
    'padded-blocks': [2, 'never'],
    'quote-props': [2, 'consistent'],
    'quotes': [2, 'single', {allowTemplateLiterals: true}],
    'semi': 2,
    'semi-spacing': 2,
    'space-before-blocks': 2,
    'space-before-function-paren': [
      2,
      {
        asyncArrow: 'always',
        anonymous: 'never',
        named: 'never',
      },
    ],
    'spaced-comment': [2, 'always'],
    'switch-colon-spacing': 2,

    'curly': ['error'],
    'dot-notation': ['error'],
    'no-sequences': [1],
    'no-useless-concat': [1],
    'no-useless-escape': [1],
    'vars-on-top': [1],
    'yoda': [1],
    'capitalized-comments': [1, 'always', {ignoreConsecutiveComments: true}],
    'indent': ['error', 2],
  },
};
