#!/usr/bin/env bash

SECONDS=0
while read -r line; do
    http_status=$(curl -o /dev/null -s -w "%{response_code}" "$line")
    printf "%s %s\n" "$line" "$http_status"
done <"$1"
echo "Elapsed time: $SECONDS seconds" >/dev/stderr
