#!/usr/bin/env bash
#
# Print title, length, and description of episodes from the latest spreadsheets
# using a case insensitive search.
#
# Put title and length on one line, then an indented and formatted description
#
# If you get too many results, copy/paste a portion of the title string
# from one of the results

cd "$WS" || exit
./listEpisodes.sh -f "$@"
