#!/usr/bin/env bash
# Fix awk syntax errors so awkfiles work with prettier-plugin-awk
#
# shellcheck disable=SC2016

sd 'split \(' 'split(' "$@"
sd 'match \(' 'match(' "$@"
sd 'printf \(' 'printf(' "$@"
sd 'substr \(' 'substr(' "$@"
sd 'gsub \(' 'gsub(' "$@"
sd ' sub \(' ' sub(' "$@"
sd ' close \(' ' close(' "$@"

sd -F 'split($0,fld,"\/")' 'split($0,fld,"/")' "$@"
sd -F 'split($0,fld,"\|")' 'split($0,fld,"|")' "$@"
sd -F 'RS="\<"' 'RS="<"' "$@"
