#!/usr/bin/env bash
# Install all Rust apps
# If you install new ones, add them below

# Prevent cascading or pipe failures
set -euo pipefail

# trap and locate errors that might arise from pipefail
trap 'printf "${ERROR} at or near line %s:\n\t%s\n" \
    "$LINENO" "$BASH_COMMAND" >&2' ERR

# trap ctrl-c -- call cleanup and exit
trap 'cleanup; exit 130' INT
trap 'cleanup; exit 143' TERM
#
function cleanup() {
    stty sane
    # Safe because it's created if missing
    rm -rf ~/.cargo/releases
    printf "\n"
}

ERROR="\e[0;31m[Error]\e[0m"
WARNING="\e[0;33m[Warning]\e[0m"

# shellcheck disable=SC2059
if ! command -v rustup &>/dev/null; then
    printf "${WARNING} Rust is not installed\n"
    cat <<EOF

Before you can proceed, install Rust by using rustup:

Run the following in your terminal:
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
then follow the on-screen instructions.

EOF
    exit 0
fi

# Make a directory to use for installing releases
mkdir -p ~/.cargo/releases
cd ~/.cargo/releases || exit 1

# First update rustup and the rust toolchain
rustup update

cargo install --locked bat
bat cache --build

cargo install czkawka_cli
cargo install eza
cargo install fclones
cargo install fd-find
cargo install hexyl

# Helix
if [[ -d ~/Projects/helix ]]; then
    cd ~/Projects/helix || exit 1
    git pull
    # Build optimized version
    cargo install \
        --profile opt \
        --config 'build.rustflags="-C target-cpu=native"' \
        --path helix-term \
        --locked
    # Ensure runtime symlink exists
    [[ ! -L ~/.config/helix/runtime ]] &&
        ln -s "$PWD/runtime" ~/.config/helix/runtime
    cd - >/dev/null
else
    # shellcheck disable=SC2059
    printf "${WARNING} ~/Projects/helix does not exist,skipping\n"
fi

cargo install lsd

# Lychee
# Get the latest release download URL
download_url=$(curl -s "https://api.github.com/repos/lycheeverse/lychee/releases/latest" |
    jq -r '.assets[] | select(.name == "lychee-arm64-macos.tar.gz") | .browser_download_url')
curl -sL "$download_url" -o lychee-arm64-macos.tar.gz
tar -xzf lychee-arm64-macos.tar.gz lychee
mv lychee ~/.cargo/bin
rm -f lychee-arm64-macos.tar.gz

cargo install prettydiff --version 0.6.4
cargo install ripgrep
cargo install rm-improved
cargo install sd
cargo install stdrename
cargo install tealdeer
tldr --update

cargo install rust_tree
cargo install xls2txt
cargo install xsv
cargo install zeitfetch
cargo install zet

[[ "$(hostname)" == "Monarch.local" ]] && exit
[[ "$(hostname)" == "Marleau.local" ]] && exit
# Only on Irene and Holmes
cargo install broot
cargo install diffr
cargo install difftastic
cargo install git-delta
cargo install hyperfine
cargo install mdbook
cargo install --locked miniserve
cargo install --locked nu
cargo install stylua
cargo install tokei
