#!/usr/bin/env bash
# shellcheck disable=SC2013,SC2059

# Run commands on accounts in ${HOME}/.accounts using ssh
#   -m      Only on accounts containing monty
#   -j      Only on accounts containing junew
#   -s str  Only on accounts containing str

accountsFile="${HOME}/.accounts"

if [ ! -f "${accountsFile}" ]; then
    printf "[Error] Accounts file ${accountsFile} not found\n"
    exit 1
fi

while getopts ":jms:" opt; do
    case $opt in
    j)
        ACCOUNT="junew@"
        ;;
    m)
        ACCOUNT="monty@"
        ;;
    s)
        ACCOUNT="$OPTARG"
        ;;
    :)
        printf "[Error] Option -$OPTARG requires an argument\n" >&2
        exit 1
        ;;
    *)
        printf "==> Ignoring invalid option: -%s\n" "$OPTARG" >&2
        ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
    printf "[Error] No command to execute\n"
    exit 1
fi

printf "Running '$*' in ${ACCOUNT:-all} accounts on home machines\n"
read -r -p "==> Run without checking first? [y/N]" UNSAFE

for i in $(grep -v ^# "${accountsFile}" | grep -i "${ACCOUNT:-@}"); do
    if [ "$UNSAFE" = "y" ]; then
        printf "\n==> ${i}\n"
        ssh -o ConnectTimeout=10 "${i}".local "$@"
    else
        read -r -p "==> Run on ${i}? [y/N]" YESNO
        if [ "$YESNO" != "y" ]; then
            printf "Skipping...\n"
        else
            ssh -o ConnectTimeout=10 "${i}".local "$@"
        fi
    fi
done
