#!/usr/bin/env bash

source "$WS/waitUntil.function"

# Default to eza if no arguments provided
if [ $# -eq 0 ]; then
    set -- eza
fi

# Display all Vivid themes
for theme in $(vivid themes); do
    if waitUntil -Y "\nDisplay $theme?"; then
        LS_COLORS=$(vivid generate $theme)
        "$@"
    fi
done
