#!/usr/bin/env bash
# Install scripts in CotEditor directory
#
# IMPORTANT: Depends on only top level scripts containing '%%%'

SCRIPTDIR="$HOME/Library/Application Scripts/com.coteditor.CotEditor"
LIBDIR="$SCRIPTDIR/_lib"

echo "The script directory is:"
echo "\"$SCRIPTDIR"\" | sd "$HOME" '~'
echo ""

if [[ -d $SCRIPTDIR ]]; then
    for file in $(rg -l '%%%' -t sh); do
        cp -p "$file" "$SCRIPTDIR" && touch "$SCRIPTDIR/$file"
    done

    mkdir -p "$LIBDIR"
    for file in $(rg --files-without-match '%%%' --type sh); do
        cp -p "$file" "$LIBDIR" && touch "$LIBDIR/$file"
    done

    echo "These scripts were copied:"
    # shellcheck disable=SC2035
    eza *sh
    echo ""

    echo "Check for any old files or other discrepancies:"
    eza -lT "$SCRIPTDIR"
else
    echo "The script directory does not exist, no scripts were copied."
fi
