#!/usr/bin/env bash
# Install scripts in CotEditor directory
#
# IMPORTANT: Depends on only top level scripts containing '%%%'

SCRIPTDIR="$HOME/Library/Application Scripts/com.coteditor.CotEditor"
LIBDIR="$SCRIPTDIR/_lib"

printf "The script directory is:\n"
printf '"%s"\n' "${SCRIPTDIR/$HOME/\$HOME}"
printf "\n"

if [[ -d $SCRIPTDIR ]]; then
    # Identify top level scripts (those with '%%%')
    rg -l -d 1 '%%%' -t sh | while read -r file; do
        cp -p "$file" "$SCRIPTDIR"
    done

    mkdir -p "$LIBDIR"

    # Identify library scripts (those without '%%%')
    rg --files-without-match -d 1 '%%%' --type sh | while read -r file; do
        cp -p "$file" "$LIBDIR"
    done

    printf "These scripts were copied:\n"
    # shellcheck disable=SC2035
    eza *.sh
    printf "\n"

    printf "Check for any old files or other discrepancies:\n"
    eza -lT "$SCRIPTDIR"
else
    printf "The script directory does not exist, no scripts were copied.\n"
fi
