#!/usr/bin/env bash

function tryTheme {
    read -r -p "Try $1? [Y/n] " YESNO
    if [ "$YESNO" = "n" ]; then
        printf "Skipping $1...\n"
    else
        printf "Applying $1...\n"
        kitty +kitten themes --config-file-name themes.conf $@
    fi
}

tryTheme "1984 Dark"
tryTheme "Afterglow"
tryTheme "Catppuccin-Mocha"
tryTheme "Corvine"
tryTheme "GitHub Dark Colorblind"
tryTheme "GitHub Dark High Contrast"
tryTheme "Ir Black"
tryTheme "Jellybeans"
tryTheme "kanagawabones"
tryTheme "Kaolin Dark"
tryTheme "Leaf Dark"
tryTheme "Monokai"
tryTheme "Nightfly"
tryTheme "Nightfox"
tryTheme "Night Owl"
tryTheme "One Half Dark"
tryTheme "PaperColor Dark"
tryTheme "Rosé Pine"
tryTheme "Rosé Pine Moon"
tryTheme "Snazzy"
tryTheme "Sourcerer"
tryTheme "Substrata"
tryTheme "Tokyo Night"
tryTheme "YsDark"
tryTheme "zenbones_dark"
