new_tab Spelltower
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/Spelltower_Magic
launch zsh
cd ~/Projects/Spelltower_Magic

new_tab TV
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday
launch zsh
cd ~/Projects/WhatsStreamingToday

new_tab Nvim
layout tall:bias=68;full_size=2
launch zsh
cd ~/dotfiles/config.dir/nvim/lua/plugins
launch zsh
cd ~/dotfiles/config.dir/nvim

new_tab Acorn
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Acorn
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Acorn/Acorn-columns

new_tab BBox
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/BBox
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/BBox/BBox-columns

new_tab MHz
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/MHz
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/MHz/MHz-columns

new_tab OPB
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/OPB
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/OPB/OPB-columns

new_tab Tests
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/tests
launch zsh
cd ~/Projects/tests

new_tab Kitty
layout tall:bias=68;full_size=2
launch zsh
cd ~/dotfiles/config.dir/kitty
launch zsh
cd ~/dotfiles/config.dir/kitty/notgit
