new_tab TV
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday
launch zsh
cd ~/Projects/CountEpisodes

new_tab Spelltower http
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/Spelltower_http
launch zsh
cd ~/Projects/Spelltower_http

new_tab Spelltower main
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/Spelltower_Magic/hidden/games
launch zsh
cd ~/Projects/Spelltower_Magic

new_tab Tests
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/tests
launch zsh
cd ~/Projects/tests

new_tab Quartile
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/quartile
launch zsh
cd ~/Projects/quartile

new_tab Pangram
layout tall:bias=68;full_size=2
launch zsh
cd /Users/monty/Projects/pangram
launch zsh
cd /Users/monty/Projects/pangram

new_tab Nvim
layout tall:bias=68;full_size=2
launch zsh
cd ~/dotfiles/config.dir/nvim/lua/plugins
launch zsh
cd ~/dotfiles/config.dir/nvim

new_tab Kitty
layout tall:bias=68;full_size=2
launch zsh
cd ~/dotfiles/config.dir/kitty/notgit
launch zsh
cd ~/dotfiles/config.dir/kitty
