new_tab TV
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday
launch zsh
cd ~/Projects/CountEpisodes

new_tab Acorn
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Acorn
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Acorn/Acorn-columns

new_tab BBox
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/BBox
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/BBox/BBox-columns

new_tab MHz
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/MHz
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/MHz/MHz-columns

new_tab OPB
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/OPB
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/OPB/OPB-columns

new_tab Dotfiles
layout tall:bias=68;full_size=2
launch zsh
cd ~/dotfiles
launch zsh
cd ~/dotfiles/config.dir

new_tab SQ
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Squishers
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Squishers

new_tab RS
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Squishers/rs_squisher
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Squishers/rs_squisher

new_tab PY
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Squishers/py_squisher
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Squishers/py_squisher

new_tab GO
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Squishers/go_squisher
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Squishers/go_squisher

new_tab Kitty
layout tall:bias=68;full_size=2
launch zsh
cd ~/dotfiles/config.dir/kitty
launch zsh
cd ~/dotfiles/config.dir/kitty/notgit
