new_tab TV
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday
launch zsh
cd ~/Projects/CountEpisodes

new_tab Spelltower http
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/Spelltower_http
launch zsh
cd ~/Projects/Spelltower_http

new_tab Spelltower main
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/Spelltower_Magic/hidden/games
launch zsh
cd ~/Projects/Spelltower_Magic

new_tab Neovim
layout tall:bias=68;full_size=2
launch zsh
cd ~/dotfiles/config.dir/nvim/lua/plugins
launch zsh
cd ~/dotfiles/config.dir/nvim

new_tab BBox
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/BBox
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/BBox

new_tab Tests
layout tall:bias=68;full_size=2
launch zsh
cd ~/bin/tests
launch zsh
cd ~/bin/tests

new_tab Kitty
layout tall:bias=68;full_size=2
launch zsh
cd ~/dotfiles/config.dir/kitty/notgit
launch zsh
cd ~/dotfiles/config.dir/kitty
