new_tab TV
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday
launch zsh
cd ~/Projects/CountEpisodes

new_tab Dotfiles
layout tall:bias=68;full_size=2
launch zsh
cd ~/dotfiles
launch zsh
cd ~/.config

new_tab SQ
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Squishers
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Squishers

new_tab RS
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Squishers/rs_squisher
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Squishers/rs_squisher

new_tab PY
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Squishers/py_squisher
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Squishers/py_squisher

new_tab GO
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Squishers/go_squisher
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Squishers/go_squisher

new_tab SW
layout tall:bias=68;full_size=2
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Squishers/sw_squisher
launch zsh
cd ~/Projects/WhatsStreamingToday/sitemaps/Squishers/sw_squisher

new_tab UP
layout tall:bias=68;full_size=2
launch zsh
cd /Users/monty/Projects/tests/updateTests
launch zsh
cd /Users/monty/Projects/tests/updateTests

new_tab Kitty
layout tall:bias=68;full_size=2
launch zsh
cd ~/dotfiles/config.dir/kitty
launch zsh
cd ~/dotfiles/config.dir/kitty/notgit
